/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TabSpacesPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// src/types.ts
var COMPLETED_PARENT_ID = "__completed__";
var DEFAULT_SETTINGS = {
  confirmBeforeComplete: true,
  defaultOpenBehavior: { mode: "tab" },
  titleOverflow: "truncate",
  hideTabHeaders: false
};
var DEFAULT_DATA = {
  items: [],
  settings: DEFAULT_SETTINGS
};
var VIEW_TYPE_WORKING_TABS = "working-tabs-view";
function generateId() {
  return Date.now().toString(36) + Math.random().toString(36).substring(2, 9);
}

// src/store.ts
var LEGACY_UNSORTED_PARENT_ID = "__unsorted__";
var TabSpacesStore = class {
  constructor(plugin) {
    this.listeners = [];
    this.plugin = plugin;
    this.data = { items: [], settings: { ...DEFAULT_SETTINGS } };
  }
  async load() {
    var _a, _b;
    const saved = await this.plugin.loadData();
    this.data = {
      items: (_a = saved == null ? void 0 : saved.items) != null ? _a : DEFAULT_DATA.items,
      settings: { ...DEFAULT_SETTINGS, ...(_b = saved == null ? void 0 : saved.settings) != null ? _b : {} }
    };
    for (const item of this.data.items) {
      if (item.parentId === LEGACY_UNSORTED_PARENT_ID)
        item.parentId = null;
    }
  }
  async save() {
    await this.plugin.saveData(this.data);
  }
  onChange(listener) {
    this.listeners.push(listener);
    return () => {
      this.listeners = this.listeners.filter((l) => l !== listener);
    };
  }
  notify() {
    for (const listener of this.listeners)
      listener();
  }
  get settings() {
    return this.data.settings;
  }
  async updateSettings(patch) {
    this.data.settings = { ...this.data.settings, ...patch };
    await this.save();
    this.notify();
  }
  get items() {
    return this.data.items;
  }
  find(id) {
    return this.data.items.find((i) => i.id === id);
  }
  children(parentId) {
    return this.data.items.filter((item) => item.parentId === parentId).sort((a, b) => a.order - b.order);
  }
  nextOrder(parentId) {
    const siblings = this.children(parentId);
    return siblings.length > 0 ? Math.max(...siblings.map((s) => s.order)) + 1 : 0;
  }
  /** Default title for a freshly-created group/section -- "Group 1",
   * "Section 1", etc. -- since neither is named up front (a group is
   * auto-created the moment a pane appears; a section is created instantly
   * with no naming prompt). Renaming later is just the normal rename flow. */
  nextDefaultTitle(type) {
    const count = this.data.items.filter((n) => n.type === type).length;
    const label = type === "group" ? "Group" : "Section";
    return `${label} ${count + 1}`;
  }
  async addSection(title, parentId = null) {
    const node = {
      id: generateId(),
      type: "section",
      title,
      parentId,
      order: this.nextOrder(parentId),
      collapsed: false
    };
    this.data.items.push(node);
    await this.save();
    this.notify();
    return node;
  }
  async addGroup(title, parentId = null, openBehavior = this.data.settings.defaultOpenBehavior) {
    const node = {
      id: generateId(),
      type: "group",
      title,
      parentId,
      order: this.nextOrder(parentId),
      collapsed: false,
      openBehavior: { ...openBehavior }
    };
    this.data.items.push(node);
    await this.save();
    this.notify();
    return node;
  }
  async addTab(groupId, tabKey, title, options = {}) {
    const node = {
      id: generateId(),
      type: "tab",
      title,
      parentId: groupId,
      order: this.nextOrder(groupId),
      tabKey,
      filePath: options.filePath,
      viewState: options.viewState
    };
    this.data.items.push(node);
    await this.save();
    this.notify();
    return node;
  }
  /** The user-facing rename (dblclick, F2, "Rename" menu item). Marks a tab's
   * title as overridden so reconcile's live-title sync (see syncTitle) never
   * clobbers a name the user deliberately chose. */
  async rename(id, title) {
    const node = this.find(id);
    if (!node)
      return;
    node.title = title;
    if (node.type === "tab")
      node.titleOverridden = true;
    await this.save();
    this.notify();
  }
  /** Reconcile-only: keeps a tab's title in step with its live view (a
   * renamed Terminus tab, a browser tab's title loading in, etc.), unless
   * the user has explicitly renamed it via `rename()` above. */
  async syncTitle(id, title) {
    const node = this.find(id);
    if (!node || node.type !== "tab" || node.titleOverridden || node.title === title)
      return;
    node.title = title;
    await this.save();
    this.notify();
  }
  /** Reconcile-only: keeps a tab's full view state in step with its live
   * view. Titles get their own explicit sync (with an override guard) since
   * users can rename those; there's no equivalent user-facing edit for view
   * state, so it's always kept fresh -- this is the only place a URL lives
   * for a browser tab, so without it, navigating within an already-tracked
   * tab would silently go stale and reopening it later would land back on
   * whatever page was open when it was first captured, not wherever it
   * actually ended up. JSON-compares before writing so an unchanged tab
   * (the common case on most reconcile passes) doesn't touch disk. */
  async syncViewState(id, viewState) {
    const node = this.find(id);
    if (!node || node.type !== "tab")
      return;
    const next = JSON.stringify(viewState);
    if (JSON.stringify(node.viewState) === next)
      return;
    node.viewState = viewState;
    await this.save();
    this.notify();
  }
  /** Follows a vault file rename into every tab tracking it (`filePath` and
   * `tabKey` are the same string for file-backed tabs) -- without this, a
   * renamed file's old path stops matching anything open, so the tab looks
   * closed to reconcile and either gets knocked out of its group as a
   * "new" ad hoc one, or, if marked done, is left permanently pointing at a
   * path that no longer exists. */
  async remapTabPath(oldPath, newPath, newTitle) {
    var _a;
    let changed = false;
    for (const node of this.data.items) {
      if (node.type !== "tab" || node.filePath !== oldPath)
        continue;
      node.filePath = newPath;
      node.tabKey = newPath;
      if (!node.titleOverridden)
        node.title = newTitle;
      const state = (_a = node.viewState) == null ? void 0 : _a.state;
      if (state && state.file === oldPath)
        state.file = newPath;
      changed = true;
    }
    if (!changed)
      return;
    await this.save();
    this.notify();
  }
  /** Reconcile-only: re-derives a tab's stored order from its live tab-strip
   * position, so dragging the actual Obsidian tabs updates the sidebar too.
   * No-ops if the order already matches, so a normal reconcile pass with
   * nothing to fix doesn't write to disk. */
  async setOrder(id, order) {
    const node = this.find(id);
    if (!node || node.order === order)
      return;
    node.order = order;
    await this.save();
    this.notify();
  }
  async toggleCollapsed(id) {
    const node = this.find(id);
    if (!node || node.type !== "group" && node.type !== "section")
      return;
    node.collapsed = !node.collapsed;
    await this.save();
    this.notify();
  }
  /** Purely cosmetic -- never closes or removes the tab. */
  async toggleDone(id) {
    const node = this.find(id);
    if (!node || node.type !== "tab")
      return;
    node.done = !node.done;
    await this.save();
    this.notify();
  }
  async setDescription(id, description) {
    const node = this.find(id);
    if (!node || node.type !== "group" && node.type !== "section")
      return;
    node.description = description;
    await this.save();
    this.notify();
  }
  async setOpenBehavior(id, openBehavior) {
    const node = this.find(id);
    if (!node || node.type !== "group")
      return;
    node.openBehavior = { ...openBehavior };
    await this.save();
    this.notify();
  }
  /** Tracks the pane a group is currently occupying; cleared once the pane closes. */
  async setHomeLeaf(id, leafId) {
    const node = this.find(id);
    if (!node || node.type !== "group")
      return;
    node.homeLeafId = leafId;
    await this.save();
    this.notify();
  }
  async toggleHidden(id) {
    const node = this.find(id);
    if (!node || node.type !== "group" && node.type !== "section")
      return;
    node.hidden = !node.hidden;
    await this.save();
    this.notify();
  }
  groupByHomeLeaf(leafId) {
    return this.data.items.find((i) => i.type === "group" && i.homeLeafId === leafId);
  }
  /** Removes a node. If it's a group/section, its descendants are removed too. */
  async remove(id) {
    const idsToRemove = /* @__PURE__ */ new Set([id]);
    let grew = true;
    while (grew) {
      grew = false;
      for (const item of this.data.items) {
        if (item.parentId && idsToRemove.has(item.parentId) && !idsToRemove.has(item.id)) {
          idsToRemove.add(item.id);
          grew = true;
        }
      }
    }
    this.data.items = this.data.items.filter((i) => !idsToRemove.has(i.id));
    await this.save();
    this.notify();
  }
  /** Returns true if `ancestorId` is `id` itself or one of its ancestors. */
  isDescendantOf(id, ancestorId) {
    let current = this.find(id);
    while (current) {
      if (current.id === ancestorId)
        return true;
      current = current.parentId ? this.find(current.parentId) : void 0;
    }
    return false;
  }
  /**
   * Moves `id` to be a child of `newParentId`, inserted at `index` among its
   * new siblings. Reordering within the same parent, moving a tab to a
   * different group, and moving a group into/out of a section are all just
   * this one operation -- no special-casing needed.
   */
  async moveInto(id, newParentId, index) {
    const node = this.find(id);
    if (!node)
      return;
    if (newParentId && (newParentId === id || this.isDescendantOf(newParentId, id)))
      return;
    node.parentId = newParentId;
    const siblings = this.children(newParentId).filter((s) => s.id !== id);
    siblings.splice(Math.max(0, Math.min(index, siblings.length)), 0, node);
    siblings.forEach((s, i) => {
      s.order = i;
    });
    await this.save();
    this.notify();
  }
  get completed() {
    return this.children(COMPLETED_PARENT_ID);
  }
  /**
   * Marks a group done: remembers where it lived (so Restore can put it
   * back), moves it under the reserved COMPLETED_PARENT_ID bucket. Does not
   * touch any live leaves -- callers (leaf-sync) detach those first.
   */
  async complete(id) {
    const node = this.find(id);
    if (!node || node.type !== "group")
      return;
    node.lastParentId = node.parentId;
    node.homeLeafId = void 0;
    node.completedAt = Date.now();
    await this.moveInto(id, COMPLETED_PARENT_ID, this.children(COMPLETED_PARENT_ID).length);
  }
  /** Restores a completed group to its original section, or root if that's gone. */
  async restore(id) {
    const node = this.find(id);
    if (!node || node.type !== "group")
      return;
    const target = node.lastParentId && this.find(node.lastParentId) ? node.lastParentId : null;
    node.completedAt = void 0;
    await this.moveInto(id, target, this.children(target).length);
  }
};

// src/leaf-sync.ts
var import_obsidian = require("obsidian");
function getLeafId(leaf) {
  return leaf.id;
}
function titleFromPath(path) {
  var _a;
  const base = (_a = path.split("/").pop()) != null ? _a : path;
  return base.replace(/\.[^./]+$/, "") || base;
}
var LeafSync = class {
  constructor(plugin, store) {
    this.plugin = plugin;
    this.store = store;
    this.reconcileRunning = false;
    this.reconcileQueued = false;
    /** Groups currently mid-open (see openGroup) -- reconcile skips syncing
     * their tab list until opening finishes, to avoid treating "not created
     * yet" the same as "closed". */
    this.openingGroups = /* @__PURE__ */ new Set();
  }
  get app() {
    return this.plugin.app;
  }
  get workspace() {
    return this.plugin.app.workspace;
  }
  /**
   * Identifies a leaf for tracking purposes, whether or not it's backed by a
   * vault file -- a terminal, an embedded browser tab, a canvas, or any other
   * plugin's custom view is just as much a "tab" as a note is.
   *
   * The file path is read out of the leaf's *stored* view state instead of
   * `leaf.view instanceof FileView`, because a background pane's view is
   * often a lightweight `DeferredView` stand-in (not yet instantiated as a
   * real MarkdownView/FileView) until the user actually clicks into it, so
   * an instanceof check would silently skip every leaf in any split that
   * isn't currently focused. The path is also verified against the vault --
   * some non-file views happen to store an unrelated string under a `file`
   * key too, which would otherwise get misread as a real path.
   */
  getTabIdentity(leaf) {
    var _a, _b;
    const viewState = leaf.getViewState();
    const rawFile = (_a = viewState.state) == null ? void 0 : _a.file;
    const path = typeof rawFile === "string" && this.app.vault.getAbstractFileByPath(rawFile) instanceof import_obsidian.TFile ? rawFile : void 0;
    if (path)
      return { key: path, path, title: titleFromPath(path) };
    const leafId = (_b = getLeafId(leaf)) != null ? _b : `${Date.now()}-${Math.random()}`;
    const title = leaf.getDisplayText() || viewState.type || "Untitled";
    return { key: `${viewState.type}:${leafId}`, title };
  }
  /** The reverse of clicking a tab in the sidebar: given a leaf that just
   * became active in the workspace, finds the stored tab tracking it (if
   * any), so the sidebar can highlight/reveal it in turn. */
  findTabForLeaf(leaf) {
    const key = this.getTabIdentity(leaf).key;
    return this.store.items.find((i) => i.type === "tab" && i.tabKey === key);
  }
  start() {
    this.workspace.onLayoutReady(() => void this.reconcile());
    this.plugin.registerEvent(this.workspace.on("layout-change", () => void this.reconcile()));
    this.plugin.registerInterval(window.setInterval(() => void this.reconcile(), 3e3));
    this.plugin.registerEvent(
      this.app.vault.on("rename", (file, oldPath) => {
        if (file instanceof import_obsidian.TFile)
          void this.store.remapTabPath(oldPath, file.path, titleFromPath(file.path));
      })
    );
  }
  /**
   * `layout-change` fires often (any tab/pane change), and a reconcile pass
   * does several sequential awaited store mutations, each of which writes
   * to disk. Without this guard, a second layout-change firing mid-pass
   * would start an overlapping reconcile reading/writing the same data
   * concurrently -- interleaved writes from two passes is exactly what
   * produced the duplicate/missing tabs seen while testing this. Instead,
   * a call that arrives while one is already running just requests exactly
   * one more full pass after the current one finishes.
   */
  async reconcile() {
    if (this.reconcileRunning) {
      this.reconcileQueued = true;
      return;
    }
    this.reconcileRunning = true;
    try {
      await this.doReconcile();
    } finally {
      this.reconcileRunning = false;
      if (this.reconcileQueued) {
        this.reconcileQueued = false;
        void this.reconcile();
      }
    }
  }
  /**
   * Keeps live-tracking state honest against reality. Runs on every
   * layout-change plus once at startup, since that's also how a group gets
   * reclaimed after a restart: Obsidian's own session restore reopens last
   * session's leaves (under new, unrelated leaf ids) before this plugin
   * runs, so matching a stored group back to its pane has to go by the
   * tab's identity key, not leaf id.
   *
   * Every open pane is, structurally, already a group of tabs -- so any pane
   * not claimed by an existing group becomes a brand-new one, permanent from
   * the moment it's created (no separate "Unsorted, deleted once empty"
   * bucket -- once made, it behaves exactly like one you created yourself:
   * goes dormant, not gone, when its pane closes). `leaf.parent` object
   * identity is what distinguishes one pane from another within a single
   * pass. This includes any leaf at all (a terminal, an embedded browser
   * tab, a canvas, any other plugin's view) -- not just notes.
   */
  async doReconcile() {
    var _a, _b;
    const openLeafIds = /* @__PURE__ */ new Set();
    const keyToLeaf = /* @__PURE__ */ new Map();
    const containerLeaves = /* @__PURE__ */ new Map();
    this.workspace.iterateAllLeaves((leaf) => {
      var _a2;
      const id = getLeafId(leaf);
      if (id)
        openLeafIds.add(id);
      const root = leaf.getRoot();
      if (root === this.workspace.leftSplit || root === this.workspace.rightSplit)
        return;
      if (leaf.view.getViewType() === VIEW_TYPE_WORKING_TABS)
        return;
      const identity = this.getTabIdentity(leaf);
      if (!keyToLeaf.has(identity.key))
        keyToLeaf.set(identity.key, leaf);
      const list = (_a2 = containerLeaves.get(leaf.parent)) != null ? _a2 : [];
      list.push({ leaf, identity });
      containerLeaves.set(leaf.parent, list);
    });
    const tabByKey = /* @__PURE__ */ new Map();
    for (const item of this.store.items) {
      if (item.type === "tab" && item.tabKey)
        tabByKey.set(item.tabKey, item);
    }
    for (const entries of containerLeaves.values()) {
      for (const { leaf, identity } of entries) {
        const tab = tabByKey.get(identity.key);
        if (!tab)
          continue;
        await this.store.syncTitle(tab.id, identity.title);
        await this.store.syncViewState(tab.id, leaf.getViewState());
      }
    }
    for (const node of this.store.items) {
      if (node.type !== "group" || !node.homeLeafId)
        continue;
      const homeLeaf = this.workspace.getLeafById(node.homeLeafId);
      if (!homeLeaf)
        continue;
      const liveKeys = ((_a = containerLeaves.get(homeLeaf.parent)) != null ? _a : []).map((e) => e.identity.key);
      if (liveKeys.length === 0)
        continue;
      const tabs = this.store.children(node.id);
      const liveTabs = tabs.filter((t) => t.tabKey && liveKeys.includes(t.tabKey)).sort((a, b) => liveKeys.indexOf(a.tabKey) - liveKeys.indexOf(b.tabKey));
      const otherTabs = tabs.filter((t) => !t.tabKey || !liveKeys.includes(t.tabKey));
      let index = 0;
      for (const tab of [...liveTabs, ...otherTabs])
        await this.store.setOrder(tab.id, index++);
    }
    for (const node of this.store.items) {
      if (node.type !== "group" || !node.homeLeafId || openLeafIds.has(node.homeLeafId))
        continue;
      const survivingTab = this.store.children(node.id).find((t) => t.tabKey && keyToLeaf.has(t.tabKey));
      const replacement = (survivingTab == null ? void 0 : survivingTab.tabKey) ? keyToLeaf.get(survivingTab.tabKey) : void 0;
      if (replacement) {
        await this.store.setHomeLeaf(node.id, getLeafId(replacement));
        continue;
      }
      await this.store.setHomeLeaf(node.id, void 0);
      for (const tab of this.store.children(node.id)) {
        if (!tab.done)
          await this.store.remove(tab.id);
      }
      if (this.store.children(node.id).length === 0)
        await this.store.remove(node.id);
    }
    const claimedContainers = /* @__PURE__ */ new Map();
    for (const node of this.store.items) {
      if (node.type !== "group" || node.homeLeafId)
        continue;
      const tabs = this.store.children(node.id);
      if (tabs.length === 0)
        continue;
      const leaves = tabs.map((t) => t.tabKey ? keyToLeaf.get(t.tabKey) : void 0);
      if (leaves.some((l) => !l))
        continue;
      const first = leaves[0];
      const firstId = getLeafId(first);
      if (!firstId)
        continue;
      await this.store.setHomeLeaf(node.id, firstId);
      this.applyHiddenClass(node);
      claimedContainers.set(first.parent, node.id);
    }
    for (const node of this.store.items) {
      if (node.type !== "group" || !node.homeLeafId)
        continue;
      const leaf = this.workspace.getLeafById(node.homeLeafId);
      if (leaf)
        claimedContainers.set(leaf.parent, node.id);
    }
    for (const [container, groupId] of claimedContainers) {
      if (this.openingGroups.has(groupId))
        continue;
      await this.syncGroupTabs(groupId, (_b = containerLeaves.get(container)) != null ? _b : []);
    }
    for (const [container, entries] of containerLeaves) {
      if (claimedContainers.has(container))
        continue;
      const group = await this.store.addGroup(this.store.nextDefaultTitle("group"), null);
      const firstId = getLeafId(entries[0].leaf);
      if (firstId)
        await this.store.setHomeLeaf(group.id, firstId);
      await this.syncGroupTabs(group.id, entries);
    }
  }
  /** Adds any of `entries` not already tracked under `groupId`, and prunes
   * any currently-tracked, non-done tab whose leaf is no longer among them.
   * A tab marked done was deliberately closed via the checkbox, not closed
   * externally -- its leaf being gone is expected, not a signal to forget it. */
  async syncGroupTabs(groupId, entries) {
    const openEntries = new Map(entries.map((e) => [e.identity.key, e]));
    for (const tab of this.store.children(groupId)) {
      if (tab.done)
        continue;
      if (!tab.tabKey || !openEntries.has(tab.tabKey))
        await this.store.remove(tab.id);
    }
    const existingKeys = new Set(this.store.children(groupId).map((t) => t.tabKey));
    for (const [key, entry] of openEntries) {
      if (existingKeys.has(key))
        continue;
      await this.store.addTab(groupId, key, entry.identity.title, {
        filePath: entry.identity.path,
        viewState: entry.leaf.getViewState()
      });
    }
  }
  /**
   * Ported from Vertical Tabs' own (proven, shipped-for-years) approach:
   * toggle a class on the specific pane, then let a *declarative* CSS
   * `:has()` selector (see styles.css) cascade the collapse up through
   * however many nested splits are affected -- not JavaScript walking the
   * DOM. An earlier attempt tried to replicate that cascade ourselves by
   * recursively adjusting flex values, which occasionally corrupted the
   * sizing of *other*, unrelated panes; CSS re-evaluating `:has()` on its
   * own, with nothing but a class toggle from us, can't drift out of sync
   * with the DOM the way hand-rolled JS state can.
   */
  /** A group counts as hidden either because it was individually marked so,
   * or because the section it's filed under was -- bulk-hiding a section
   * doesn't overwrite each group's own flag, so un-hiding the section later
   * restores whatever each group's individual state actually was. */
  isEffectivelyHidden(group) {
    if (group.hidden)
      return true;
    const parent = group.parentId ? this.store.find(group.parentId) : void 0;
    return Boolean((parent == null ? void 0 : parent.type) === "section" && parent.hidden);
  }
  applyHiddenClass(group) {
    if (!group.homeLeafId)
      return;
    const leaf = this.workspace.getLeafById(group.homeLeafId);
    const tabsEl = leaf == null ? void 0 : leaf.view.containerEl.closest(".workspace-tabs");
    tabsEl == null ? void 0 : tabsEl.toggleClass("working-tabs-hidden-pane", this.isEffectivelyHidden(group));
  }
  async toggleGroupHidden(id) {
    await this.store.toggleHidden(id);
    const group = this.store.find(id);
    if (group)
      this.applyHiddenClass(group);
  }
  /** Same mechanism as toggleGroupHidden, but for every group filed under a
   * section at once -- each group's own `hidden` flag is untouched, only
   * the section's is flipped, and isEffectivelyHidden combines the two. */
  async toggleSectionHidden(id) {
    await this.store.toggleHidden(id);
    for (const group of this.store.children(id)) {
      if (group.type === "group")
        this.applyHiddenClass(group);
    }
  }
  /** For 'split', resolves the anchor pane ourselves and calls
   * `createLeafBySplit` explicitly instead of `getLeaf('split', direction)`
   * -- the same public API `getLeaf` uses internally (`getLeaf('split', d)`
   * is just `createLeafBySplit(getMostRecentLeaf(), d)` under the hood), but
   * going through it directly is one less layer to trust, and matches the
   * mechanism the workspace drag-and-drop feature already uses successfully. */
  createLeafFor(behavior) {
    var _a, _b;
    switch (behavior.mode) {
      case "split": {
        const anchor = this.workspace.getMostRecentLeaf();
        if (anchor)
          return this.workspace.createLeafBySplit(anchor, (_a = behavior.direction) != null ? _a : "vertical");
        return this.workspace.getLeaf("split", (_b = behavior.direction) != null ? _b : "vertical");
      }
      case "window":
        return this.workspace.getLeaf("window");
      case "tab":
      default:
        return this.workspace.getLeaf("tab");
    }
  }
  /** Opens a brand-new, empty pane per the chosen placement -- no group
   * record is created here at all. The next reconcile pass finds the new
   * pane unclaimed and auto-creates + auto-names its group ("Group N"),
   * exactly like any other pane opened by hand; this is just the sidebar's
   * "+ New group" row shortcut for that same, already-existing path. */
  async openNewGroup(behavior) {
    const leaf = this.createLeafFor(behavior);
    await leaf.setViewState({ type: "empty", active: true });
    this.workspace.setActiveLeaf(leaf, { focus: true });
  }
  /** viewState works for any view type (terminal, web viewer, canvas, notes
   * with their scroll/mode preserved) and is preferred whenever present;
   * plain openFile() is only a fallback for simple file tabs that don't
   * have one captured. */
  async openTabInLeaf(leaf, tab) {
    if (tab.viewState) {
      await leaf.setViewState({ ...tab.viewState, active: true });
      return;
    }
    if (!tab.filePath)
      return;
    const file = this.app.vault.getAbstractFileByPath(tab.filePath);
    if (file instanceof import_obsidian.TFile)
      await leaf.openFile(file);
  }
  /** Whether a group currently has a live pane. */
  isLive(id) {
    const group = this.store.find(id);
    return Boolean((group == null ? void 0 : group.homeLeafId) && this.workspace.getLeafById(group.homeLeafId));
  }
  findOpenLeaf(tabKey) {
    if (!tabKey)
      return void 0;
    let found;
    this.workspace.iterateAllLeaves((l) => {
      if (!found && this.getTabIdentity(l).key === tabKey)
        found = l;
    });
    return found;
  }
  /** Clicking a tab in the sidebar should focus that exact tab, not just
   * whichever one happens to already be active in its pane. Opens the whole
   * group first if it isn't live yet (or this particular tab isn't open --
   * e.g. it was just un-done). */
  async focusTab(tab) {
    if (tab.type !== "tab" || !tab.parentId)
      return;
    let leaf = this.findOpenLeaf(tab.tabKey);
    if (!leaf) {
      await this.openGroup(tab.parentId);
      leaf = this.findOpenLeaf(tab.tabKey);
    }
    if (!leaf)
      return;
    await leaf.loadIfDeferred();
    this.workspace.setActiveLeaf(leaf, { focus: true });
    await this.workspace.revealLeaf(leaf);
  }
  /** Activates a group: reveals its pane if still live, otherwise reopens
   * all its tabs into a fresh pane per `behaviorOverride` or its own
   * OpenBehavior, remembering the override as its new default. */
  async openGroup(id, behaviorOverride) {
    var _a, _b;
    const group = this.store.find(id);
    if (!group || group.type !== "group")
      return;
    if (this.isEffectivelyHidden(group)) {
      if (group.hidden)
        await this.store.toggleHidden(id);
      const parent = group.parentId ? this.store.find(group.parentId) : void 0;
      if ((parent == null ? void 0 : parent.type) === "section" && parent.hidden)
        await this.store.toggleHidden(parent.id);
      this.applyHiddenClass(group);
    }
    if (group.homeLeafId) {
      const leaf = this.workspace.getLeafById(group.homeLeafId);
      if (leaf) {
        await leaf.loadIfDeferred();
        await this.workspace.revealLeaf(leaf);
        return;
      }
    }
    const tabs = this.store.children(id).filter((t) => t.viewState || t.filePath);
    if (tabs.length === 0)
      return;
    const behavior = (_a = behaviorOverride != null ? behaviorOverride : group.openBehavior) != null ? _a : this.store.settings.defaultOpenBehavior;
    if (behaviorOverride)
      await this.store.setOpenBehavior(id, behaviorOverride);
    const owner = behavior.mode === "tab" ? this.findOwningGroup((_b = this.workspace.getMostRecentLeaf()) == null ? void 0 : _b.parent, id) : void 0;
    const first = this.createLeafFor(behavior);
    if (!owner) {
      const firstId = getLeafId(first);
      if (firstId)
        await this.store.setHomeLeaf(id, firstId);
    }
    this.openingGroups.add(id);
    try {
      await this.openTabInLeaf(first, tabs[0]);
      for (const tab of tabs.slice(1)) {
        const leaf = this.workspace.createLeafInParent(first.parent, 9999);
        await this.openTabInLeaf(leaf, tab);
      }
    } finally {
      this.openingGroups.delete(id);
    }
    if (owner) {
      await this.store.remove(id);
      new import_obsidian.Notice(`"${group.title}" merged into "${owner.title}".`);
      return;
    }
    await this.workspace.revealLeaf(first);
  }
  findOwningGroup(container, excludeId) {
    if (!container)
      return void 0;
    return this.store.items.find(
      (n) => {
        var _a;
        return n.type === "group" && n.id !== excludeId && n.homeLeafId && ((_a = this.workspace.getLeafById(n.homeLeafId)) == null ? void 0 : _a.parent) === container;
      }
    );
  }
  /**
   * Opens a group's tabs anchored to a *specific* pane the user dropped it
   * onto (see TabSpacesView's workspace drop zones), instead of
   * `openGroup`'s implicit "whichever pane Obsidian thinks was most
   * recently active" -- dragging directly onto a pane's edge is exactly as
   * unambiguous as it looks, so there's no guessing involved here the way
   * there is with the "Open in..." menu's split-right/split-down choices.
   * `createLeafBySplit` is the same public API `getLeaf('split', ...)` uses
   * internally, just with an explicit anchor instead of an implicit one.
   *
   * Works the same whether the group is dormant or already live: an
   * already-live group is treated as "move this pane" -- closed at its
   * current spot first, then reopened fresh at the drop target. Its tabs'
   * viewState is kept continuously up to date (see syncViewState), so this
   * reopen is a close approximation of a true in-place relocate, without
   * the fragility of hand-rolling Obsidian's own internal split-tree
   * surgery to actually move the live pane object -- the kind of custom
   * DOM manipulation that corrupted an unrelated pane's sizing the one
   * other time this codebase tried it (see the hide-pane CSS comment above).
   */
  async openGroupAtDropTarget(id, targetLeaf, zone) {
    const group = this.store.find(id);
    if (!group || group.type !== "group")
      return;
    if (group.homeLeafId) {
      const currentLeaf = this.workspace.getLeafById(group.homeLeafId);
      if (currentLeaf && currentLeaf.parent === targetLeaf.parent)
        return;
    }
    const tabs = this.store.children(id).filter((t) => t.viewState || t.filePath);
    if (tabs.length === 0)
      return;
    this.openingGroups.add(id);
    try {
      if (group.homeLeafId && this.workspace.getLeafById(group.homeLeafId))
        await this.closeGroup(id);
      if (zone === "center") {
        const owner = this.findOwningGroup(targetLeaf.parent, id);
        if (!owner)
          return;
        for (const tab of tabs) {
          const leaf = this.workspace.createLeafInParent(targetLeaf.parent, 9999);
          await this.openTabInLeaf(leaf, tab);
        }
        await this.store.remove(id);
        new import_obsidian.Notice(`"${group.title}" merged into "${owner.title}".`);
        return;
      }
      const direction = zone === "top" || zone === "bottom" ? "horizontal" : "vertical";
      const before = zone === "top" || zone === "left";
      const first = this.workspace.createLeafBySplit(targetLeaf, direction, before);
      const firstId = getLeafId(first);
      if (firstId)
        await this.store.setHomeLeaf(id, firstId);
      await this.openTabInLeaf(first, tabs[0]);
      for (const tab of tabs.slice(1)) {
        const leaf = this.workspace.createLeafInParent(first.parent, 9999);
        await this.openTabInLeaf(leaf, tab);
      }
      await this.workspace.revealLeaf(first);
    } finally {
      this.openingGroups.delete(id);
    }
  }
  /** Closes a group's live pane (all sibling leaves in it), without touching stored data. */
  async closeGroup(id) {
    const group = this.store.find(id);
    if (!group || group.type !== "group" || !group.homeLeafId)
      return;
    const leaf = this.workspace.getLeafById(group.homeLeafId);
    if (leaf) {
      const container = leaf.parent;
      const siblings = [];
      this.workspace.iterateAllLeaves((l) => {
        if (l.parent === container)
          siblings.push(l);
      });
      for (const sibling of siblings)
        sibling.detach();
    }
    await this.store.setHomeLeaf(id, void 0);
  }
  async completeGroup(id) {
    await this.closeGroup(id);
    await this.store.complete(id);
  }
  /** Opens a blank tab in a live group's pane -- the sidebar's stand-in for
   * Obsidian's native "+" button, which lives in the tab-header row the
   * "Hide tab bar" setting hides. Not open yet -- if it's dormant in a
   * section, use "Open" first. */
  async addBlankTab(groupId) {
    var _a;
    const group = this.store.find(groupId);
    if (!group || group.type !== "group")
      return;
    let homeLeaf = group.homeLeafId ? this.workspace.getLeafById(group.homeLeafId) : null;
    if (!homeLeaf && this.store.children(groupId).length > 0) {
      await this.openGroup(groupId);
      const opened = this.store.find(groupId);
      homeLeaf = (opened == null ? void 0 : opened.type) === "group" && opened.homeLeafId ? this.workspace.getLeafById(opened.homeLeafId) : null;
      if (!homeLeaf)
        return;
    }
    if (homeLeaf) {
      const leaf2 = this.workspace.createLeafInParent(homeLeaf.parent, 9999);
      await leaf2.setViewState({ type: "empty", active: true });
      this.workspace.setActiveLeaf(leaf2, { focus: true });
      return;
    }
    const behavior = (_a = group.openBehavior) != null ? _a : this.store.settings.defaultOpenBehavior;
    const leaf = this.createLeafFor(behavior);
    const leafId = getLeafId(leaf);
    if (leafId)
      await this.store.setHomeLeaf(groupId, leafId);
    await leaf.setViewState({ type: "empty", active: true });
    this.workspace.setActiveLeaf(leaf, { focus: true });
  }
  /** Detaches a tab's live leaf (if its group is live and that tab is
   * actually open in its pane) without touching stored data -- used both by
   * the "mark done" checkbox (keep the record, just close it) and as the
   * first half of closeTab (which also forgets the record). */
  async closeLiveTabOnly(tab) {
    if (tab.type !== "tab" || !tab.parentId || !tab.tabKey)
      return;
    const group = this.store.find(tab.parentId);
    if ((group == null ? void 0 : group.type) !== "group" || !group.homeLeafId)
      return;
    const homeLeaf = this.workspace.getLeafById(group.homeLeafId);
    if (!homeLeaf)
      return;
    const container = homeLeaf.parent;
    const siblings = [];
    this.workspace.iterateAllLeaves((l) => {
      if (l.parent === container)
        siblings.push(l);
    });
    const matches = siblings.filter((l) => this.getTabIdentity(l).key === tab.tabKey);
    if (matches.some((l) => getLeafId(l) === group.homeLeafId)) {
      const replacement = siblings.find((l) => !matches.includes(l));
      await this.store.setHomeLeaf(group.id, replacement ? getLeafId(replacement) : void 0);
    }
    for (const match of matches)
      match.detach();
  }
  /** How many of `tab`'s siblings (by stored order) currently have a live
   * leaf in `groupId`'s pane -- the correct index to insert/reposition
   * `tab` at, so it lands where it actually belongs instead of at the end. */
  countLiveSiblingsBefore(groupId, tab, excludeTabId) {
    const group = this.store.find(groupId);
    if (!group || group.type !== "group" || !group.homeLeafId)
      return 0;
    const homeLeaf = this.workspace.getLeafById(group.homeLeafId);
    if (!homeLeaf)
      return 0;
    const container = homeLeaf.parent;
    const openKeys = /* @__PURE__ */ new Set();
    this.workspace.iterateAllLeaves((l) => {
      if (l.parent === container)
        openKeys.add(this.getTabIdentity(l).key);
    });
    return this.store.children(groupId).filter((s) => s.id !== excludeTabId && s.order < tab.order && s.tabKey && openKeys.has(s.tabKey)).length;
  }
  /** Reopens one specific tab into its group's live pane (e.g. after
   * unchecking "done"), at the position it actually belongs among its
   * currently-open siblings -- not just appended at the end. Does nothing
   * if the group isn't currently live; the tab will simply show up normally
   * next time the whole group opens. */
  async reopenTab(tab) {
    if (tab.type !== "tab" || !tab.parentId)
      return;
    const group = this.store.find(tab.parentId);
    if ((group == null ? void 0 : group.type) !== "group" || !group.homeLeafId)
      return;
    const homeLeaf = this.workspace.getLeafById(group.homeLeafId);
    if (!homeLeaf)
      return;
    const index = this.countLiveSiblingsBefore(group.id, tab);
    const leaf = this.workspace.createLeafInParent(homeLeaf.parent, index);
    await this.openTabInLeaf(leaf, tab);
  }
  /**
   * Repositions a tab's already-open leaf to match where it now sits in the
   * sidebar (after a drag-to-reorder, or a drag into a different group) --
   * relocating it between panes too if the group it was dropped into isn't
   * the one it was already open in.
   *
   * Obsidian has no public API for repositioning an already-open leaf, so
   * this uses the same undocumented `WorkspaceParent.removeChild`/
   * `insertChild`/`selectTabIndex` internals the Vertical Tabs plugin relies
   * on for its own tab reordering. Guarded with an existence check so it
   * quietly no-ops instead of throwing if a future Obsidian version removes
   * or renames them.
   */
  async relocateLiveLeaf(tab) {
    var _a, _b, _c;
    if (tab.type !== "tab" || !tab.parentId || !tab.tabKey)
      return;
    const group = this.store.find(tab.parentId);
    if (!group || group.type !== "group" || !group.homeLeafId)
      return;
    const homeLeaf = this.workspace.getLeafById(group.homeLeafId);
    if (!homeLeaf)
      return;
    const targetContainer = homeLeaf.parent;
    const sourceLeaf = this.findOpenLeaf(tab.tabKey);
    if (!sourceLeaf)
      return;
    const index = this.countLiveSiblingsBefore(group.id, tab, tab.id);
    const source = sourceLeaf.parent;
    const target = targetContainer;
    if (typeof source.removeChild !== "function" || typeof target.insertChild !== "function")
      return;
    source.removeChild(sourceLeaf);
    target.insertChild(index, sourceLeaf);
    (_a = target.selectTabIndex) == null ? void 0 : _a.call(target, index);
    (_c = (_b = this.workspace).requestResize) == null ? void 0 : _c.call(_b);
  }
  /** Closes one specific tab: detaches its live leaf and forgets it, same as
   * closing a browser tab. Without the detach half, "removing" a tab that's
   * still genuinely open would just have reconcile() re-add it right back
   * under Unsorted on the next pass. */
  async closeTab(tab) {
    await this.closeLiveTabOnly(tab);
    await this.store.remove(tab.id);
    if (tab.parentId)
      await this.removeGroupIfEmpty(tab.parentId);
  }
  /** A group left with nothing at all -- no live tabs, no done ones kept on
   * purpose -- has no reason to keep occupying the sidebar. Used after any
   * plugin-initiated tab removal; reconcile's own step 1 handles the same
   * cleanup for tabs closed natively in Obsidian. */
  async removeGroupIfEmpty(groupId) {
    const group = this.store.find(groupId);
    if ((group == null ? void 0 : group.type) === "group" && this.store.children(groupId).length === 0) {
      await this.store.remove(groupId);
    }
  }
};

// src/views/TabSpacesView.ts
var import_obsidian4 = require("obsidian");

// src/modals/ConfirmCompleteModal.ts
var import_obsidian2 = require("obsidian");
var ConfirmCompleteModal = class extends import_obsidian2.Modal {
  constructor(app, groupTitle, onConfirm) {
    super(app);
    this.groupTitle = groupTitle;
    this.onConfirm = onConfirm;
    this.dontAskAgain = false;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: `Complete "${this.groupTitle}"?` });
    contentEl.createEl("p", {
      text: "Its tabs will close and it moves to completed, where you can restore it anytime."
    });
    new import_obsidian2.Setting(contentEl).addButton((btn) => btn.setButtonText("Cancel").onClick(() => this.close())).addButton(
      (btn) => btn.setButtonText("Complete").setCta().onClick(() => {
        this.onConfirm(this.dontAskAgain);
        this.close();
      })
    );
    const checkboxRow = contentEl.createDiv({ cls: "working-tabs-checkbox-row" });
    const checkbox = checkboxRow.createEl("input", { attr: { type: "checkbox", id: "working-tabs-dont-ask" } });
    checkbox.addEventListener("change", () => this.dontAskAgain = checkbox.checked);
    checkboxRow.createEl("label", { text: "Don't ask again", attr: { for: "working-tabs-dont-ask" } });
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/modals/GroupDescriptionModal.ts
var import_obsidian3 = require("obsidian");
var GroupDescriptionModal = class extends import_obsidian3.Modal {
  constructor(app, heading, placeholder, initialDescription, onSubmit) {
    super(app);
    this.heading = heading;
    this.placeholder = placeholder;
    this.onSubmit = onSubmit;
    this.description = initialDescription;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: this.heading });
    new import_obsidian3.Setting(contentEl).addTextArea((text) => {
      text.setPlaceholder(this.placeholder).setValue(this.description).onChange((value) => this.description = value);
      text.inputEl.focus();
    });
    new import_obsidian3.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("Save").setCta().onClick(() => {
        this.onSubmit(this.description.trim());
        this.close();
      })
    );
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/views/TabSpacesView.ts
var PANE_DROP_CLASSES = [
  "working-tabs-pane-drop-top",
  "working-tabs-pane-drop-bottom",
  "working-tabs-pane-drop-left",
  "working-tabs-pane-drop-right",
  "working-tabs-pane-drop-center"
];
var OPEN_BEHAVIOR_MENU = [
  { label: "Split right", behavior: { mode: "split", direction: "vertical" } },
  { label: "Split down", behavior: { mode: "split", direction: "horizontal" } },
  { label: "New window", behavior: { mode: "window" } },
  { label: "New tab", behavior: { mode: "tab" } }
];
var NEW_GROUP_BEHAVIOR_MENU = OPEN_BEHAVIOR_MENU.filter((item) => item.behavior.mode !== "tab");
var TabSpacesView = class extends import_obsidian4.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
    this.draggedId = null;
    this.dropMarkedEl = null;
    this.paneDropMarkedEl = null;
    this.unsubscribe = null;
    this.visibleOrder = [];
    this.focusedId = null;
    this.completedCollapsed = true;
    this.searchQuery = "";
    this.store = plugin.store;
  }
  getViewType() {
    return VIEW_TYPE_WORKING_TABS;
  }
  getDisplayText() {
    return "Working tabs";
  }
  getIcon() {
    return "layout-panel-left";
  }
  async onOpen() {
    const container = this.contentEl;
    container.empty();
    container.addClass("working-tabs-view");
    this.searchInputEl = container.createEl("input", {
      cls: "working-tabs-search-input",
      attr: { type: "text", placeholder: "Search tabs and groups\u2026" }
    });
    this.searchInputEl.addEventListener("input", () => {
      this.searchQuery = this.searchInputEl.value;
      this.render();
    });
    this.searchInputEl.addEventListener("keydown", (evt) => {
      if (evt.key === "Escape") {
        evt.preventDefault();
        this.clearSearch();
      }
    });
    this.treeEl = container.createDiv({ cls: "working-tabs-tree", attr: { tabindex: "0" } });
    this.registerRootDropZone(this.treeEl);
    this.registerWorkspaceDropZones();
    this.treeEl.addEventListener("keydown", (evt) => this.handleKeydown(evt));
    this.unsubscribe = this.store.onChange(() => this.render());
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", (leaf) => {
        const tab = leaf && this.plugin.leafSync.findTabForLeaf(leaf);
        if (tab)
          void this.revealNode(tab);
      })
    );
    this.render();
  }
  /** The reverse of clicking a tab: when it becomes active in the workspace
   * (clicked directly, or switched to via keyboard), expand whatever
   * group/section/Completed bucket it's tucked inside so the highlighted
   * row is actually visible, not just technically focused. */
  async revealNode(node) {
    let parentId = node.parentId;
    while (parentId) {
      if (parentId === COMPLETED_PARENT_ID) {
        if (this.completedCollapsed) {
          this.completedCollapsed = false;
          this.render();
        }
        break;
      }
      const parent = this.store.find(parentId);
      if (!parent)
        break;
      if ((parent.type === "group" || parent.type === "section") && parent.collapsed) {
        await this.store.toggleCollapsed(parent.id);
      }
      parentId = parent.parentId;
    }
    this.setFocus(node.id);
  }
  clearSearch() {
    if (!this.searchQuery)
      return;
    this.searchInputEl.value = "";
    this.searchQuery = "";
    this.render();
  }
  /** A tab matches on its own title or file path; a group/section matches
   * on its own title or if any descendant matches, so a search surfaces the
   * container a hit lives in too. */
  matchesQuery(node, query) {
    var _a;
    if (node.title.toLowerCase().includes(query))
      return true;
    if (node.type === "tab")
      return ((_a = node.filePath) != null ? _a : "").toLowerCase().includes(query);
    return this.store.children(node.id).some((child) => this.matchesQuery(child, query));
  }
  async onClose() {
    var _a;
    (_a = this.unsubscribe) == null ? void 0 : _a.call(this);
  }
  // ── Rendering ────────────────────────────────────────────
  render() {
    this.contentEl.toggleClass("working-tabs-wrap-titles", this.store.settings.titleOverflow === "wrap");
    this.treeEl.empty();
    this.visibleOrder = [];
    const query = this.searchQuery.trim().toLowerCase();
    const roots = this.store.children(null).filter((n) => !query || this.matchesQuery(n, query));
    if (roots.length === 0) {
      this.treeEl.createDiv({
        cls: "working-tabs-empty",
        text: query ? "No matches." : "No groups yet -- open some tabs to create one automatically."
      });
    }
    for (const node of roots.filter((n) => n.type === "group"))
      this.renderNode(this.treeEl, node, 0, false, query);
    if (!query) {
      this.renderNewGroupRow();
      this.renderCreateSectionRow();
    }
    for (const node of roots.filter((n) => n.type === "section"))
      this.renderNode(this.treeEl, node, 0, false, query);
    this.treeEl.createDiv({ cls: "working-tabs-divider" });
    this.renderSyntheticSection(
      "Completed",
      COMPLETED_PARENT_ID,
      this.completedCollapsed,
      (v) => this.completedCollapsed = v,
      query
    );
  }
  renderNode(parentEl, node, depth, isCompleted, query) {
    if (node.type === "section")
      this.renderSection(parentEl, node, depth, query);
    else if (node.type === "group")
      this.renderGroup(parentEl, node, depth, isCompleted, query);
    else
      this.renderTab(parentEl, node, depth);
  }
  renderRowShell(parentEl, node, depth, extraCls = "") {
    const row = parentEl.createDiv({
      cls: `working-tabs-row ${extraCls}`.trim(),
      attr: { "data-node-id": node.id, style: `padding-left: ${8 + depth * 16}px`, draggable: "true" }
    });
    this.wireDrag(row, node);
    this.visibleOrder.push(node.id);
    if (node.id === this.focusedId)
      row.addClass("is-focused");
    row.addEventListener("mousedown", (evt) => {
      if (evt.target.tagName === "INPUT")
        return;
      this.setFocus(node.id);
    });
    return row;
  }
  renderSection(parentEl, node, depth, query) {
    const wrapper = parentEl.createDiv({ cls: "working-tabs-section" });
    const row = this.renderRowShell(
      wrapper,
      node,
      depth,
      `working-tabs-section-header${node.hidden ? " is-hidden-pane" : ""}`
    );
    const expanded = query ? true : !node.collapsed;
    const chevron = row.createDiv({ cls: "working-tabs-chevron" });
    (0, import_obsidian4.setIcon)(chevron, expanded ? "chevron-down" : "chevron-right");
    const textCol = row.createDiv({ cls: "working-tabs-text-col" });
    const title = textCol.createSpan({ cls: "working-tabs-title" });
    title.setText(node.title);
    this.wireRename(title, node);
    if (node.description) {
      textCol.createDiv({ cls: "working-tabs-description", text: node.description });
    }
    const actions = row.createDiv({ cls: "working-tabs-row-actions" });
    this.makeGroupActionButton(
      actions,
      node.hidden ? "eye-off" : "eye",
      node.hidden ? "Unhide all groups in this section" : "Hide all groups in this section",
      (evt) => {
        evt.stopPropagation();
        void this.plugin.leafSync.toggleSectionHidden(node.id);
      }
    );
    this.makeGroupActionButton(actions, "ellipsis-vertical", "More", (evt) => {
      evt.stopPropagation();
      this.showSectionMenu(node, evt);
    });
    this.wireRowClick(row, () => {
      if (!query)
        void this.store.toggleCollapsed(node.id);
    });
    row.addEventListener("contextmenu", (evt) => {
      evt.preventDefault();
      this.showSectionMenu(node, evt);
    });
    if (expanded) {
      const childWrap = wrapper.createDiv({ cls: "working-tabs-children" });
      const children = this.store.children(node.id).filter((c) => !query || this.matchesQuery(c, query));
      for (const child of children)
        this.renderNode(childWrap, child, depth + 1, false, query);
    }
  }
  isLive(node) {
    return Boolean(node.homeLeafId) && Boolean(this.app.workspace.getLeafById(node.homeLeafId));
  }
  renderGroup(parentEl, node, depth, isCompleted, query) {
    const wrapper = parentEl.createDiv({ cls: "working-tabs-group" });
    const live = !isCompleted && this.isLive(node);
    const row = this.renderRowShell(
      wrapper,
      node,
      depth,
      `working-tabs-group-header${live ? " is-live" : ""}${node.hidden ? " is-hidden-pane" : ""}`
    );
    const expanded = query ? true : !node.collapsed;
    const chevron = row.createDiv({ cls: "working-tabs-chevron" });
    (0, import_obsidian4.setIcon)(chevron, expanded ? "chevron-down" : "chevron-right");
    chevron.addEventListener("click", (evt) => {
      evt.stopPropagation();
      if (!query)
        void this.store.toggleCollapsed(node.id);
    });
    const textCol = row.createDiv({ cls: "working-tabs-text-col" });
    const titleRow = textCol.createDiv({ cls: "working-tabs-title-row" });
    const title = titleRow.createSpan({ cls: "working-tabs-title" });
    title.setText(node.title);
    this.wireRename(title, node);
    const tabCount = this.store.children(node.id).length;
    titleRow.createSpan({ cls: "working-tabs-count", text: String(tabCount) });
    if (node.description) {
      textCol.createDiv({ cls: "working-tabs-description", text: node.description });
    }
    const actions = row.createDiv({ cls: "working-tabs-row-actions" });
    if (!live) {
      this.makeGroupActionButton(actions, "external-link", "Open", (evt) => {
        evt.stopPropagation();
        const menu = new import_obsidian4.Menu();
        for (const { label, behavior } of OPEN_BEHAVIOR_MENU) {
          menu.addItem(
            (item) => item.setTitle(label).onClick(() => void this.plugin.leafSync.openGroup(node.id, behavior))
          );
        }
        menu.showAtMouseEvent(evt);
      });
    }
    if (live) {
      this.makeGroupActionButton(
        actions,
        node.hidden ? "eye-off" : "eye",
        node.hidden ? "Unhide pane" : "Hide pane",
        (evt) => {
          evt.stopPropagation();
          void this.plugin.leafSync.toggleGroupHidden(node.id);
        }
      );
    }
    this.makeGroupActionButton(
      actions,
      isCompleted ? "rotate-ccw" : "check-circle",
      isCompleted ? "Restore" : "Complete",
      (evt) => {
        evt.stopPropagation();
        if (isCompleted)
          void this.store.restore(node.id);
        else
          this.requestComplete(node);
      }
    );
    this.makeGroupActionButton(actions, "ellipsis-vertical", "More", (evt) => {
      evt.stopPropagation();
      this.showGroupMenu(node, evt, isCompleted);
    });
    this.wireRowClick(row, () => void this.plugin.leafSync.openGroup(node.id));
    row.addEventListener("contextmenu", (evt) => {
      evt.preventDefault();
      this.showGroupMenu(node, evt, isCompleted);
    });
    if (expanded) {
      const childWrap = wrapper.createDiv({ cls: "working-tabs-children" });
      const children = this.store.children(node.id).filter((c) => !query || this.matchesQuery(c, query));
      for (const child of children)
        this.renderNode(childWrap, child, depth + 1, isCompleted, query);
    }
  }
  makeGroupActionButton(parent, icon, label, onClick) {
    const btn = parent.createDiv({ cls: "working-tabs-action-btn", attr: { "aria-label": label } });
    (0, import_obsidian4.setIcon)(btn, icon);
    btn.addEventListener("click", onClick);
  }
  renderTab(parentEl, node, depth) {
    const row = this.renderRowShell(parentEl, node, depth, "working-tabs-tab-row");
    const checkbox = row.createEl("input", {
      cls: "working-tabs-done-checkbox",
      attr: { type: "checkbox" }
    });
    checkbox.checked = Boolean(node.done);
    checkbox.addEventListener("click", (evt) => evt.stopPropagation());
    checkbox.addEventListener("change", () => void this.handleToggleDone(node));
    const title = row.createSpan({ cls: `working-tabs-title${node.done ? " is-done" : ""}` });
    title.setText(node.title);
    this.wireRename(title, node);
    const actions = row.createDiv({ cls: "working-tabs-row-actions" });
    this.makeGroupActionButton(actions, "x", "Close tab", (evt) => {
      evt.stopPropagation();
      void this.plugin.leafSync.closeTab(node);
    });
    this.wireRowClick(row, () => void this.plugin.leafSync.focusTab(node));
    row.addEventListener("contextmenu", (evt) => {
      evt.preventDefault();
      this.showTabMenu(node, evt);
    });
  }
  /** A group is never created directly -- it's just whatever reconcile
   * finds occupying a pane it doesn't already know about (see
   * doReconcile's step 4 and LeafSync.openNewGroup) -- so this row doesn't
   * create a group record either. It only opens a blank pane per the
   * chosen placement and lets that same auto-detection name it. */
  renderNewGroupRow() {
    const row = this.treeEl.createDiv({ cls: "working-tabs-row working-tabs-new-group-row" });
    const icon = row.createDiv({ cls: "working-tabs-chevron" });
    (0, import_obsidian4.setIcon)(icon, "plus");
    row.createSpan({ cls: "working-tabs-title", text: "New group" });
    row.addEventListener("click", (evt) => {
      const menu = new import_obsidian4.Menu();
      for (const { label, behavior } of NEW_GROUP_BEHAVIOR_MENU) {
        menu.addItem((item) => item.setTitle(label).onClick(() => void this.plugin.leafSync.openNewGroup(behavior)));
      }
      menu.showAtMouseEvent(evt);
    });
  }
  /** Heads the sections block, paired with "New group" above it. The info
   * icon is the only explanation of what a section is *for*, so it rides
   * along on the row (revealed on hover) rather than staying in the chrome. */
  renderCreateSectionRow() {
    const row = this.treeEl.createDiv({ cls: "working-tabs-row working-tabs-create-section-row" });
    const icon = row.createDiv({ cls: "working-tabs-chevron" });
    (0, import_obsidian4.setIcon)(icon, "plus");
    row.createSpan({ cls: "working-tabs-title", text: "Create a section" });
    const info = row.createSpan({ cls: "working-tabs-info-icon" });
    (0, import_obsidian4.setIcon)(info, "info");
    (0, import_obsidian4.setTooltip)(
      info,
      "Organize related groups together, e.g. by sprint or timeframe. Hide a section to tuck away every group inside it at once.",
      { placement: "top" }
    );
    row.addEventListener("click", () => void this.createSection());
  }
  // ── Synthetic Completed section ──────────────────────────
  renderSyntheticSection(title, sentinelId, collapsed, setCollapsed, query) {
    const wrapper = this.treeEl.createDiv({ cls: "working-tabs-section working-tabs-synthetic-section" });
    const row = wrapper.createDiv({ cls: "working-tabs-row working-tabs-section-header" });
    const expanded = query ? true : !collapsed;
    const chevron = row.createDiv({ cls: "working-tabs-chevron" });
    (0, import_obsidian4.setIcon)(chevron, expanded ? "chevron-down" : "chevron-right");
    const titleEl = row.createSpan({ cls: "working-tabs-title working-tabs-synthetic-title" });
    titleEl.setText(title);
    const allChildren = this.store.children(sentinelId);
    const children = allChildren.filter((c) => !query || this.matchesQuery(c, query));
    row.createSpan({ cls: "working-tabs-count", text: String(query ? children.length : allChildren.length) });
    row.addEventListener("click", () => {
      if (query)
        return;
      setCollapsed(!collapsed);
      this.render();
    });
    this.registerSentinelDropZone(row, sentinelId);
    if (expanded) {
      const childWrap = wrapper.createDiv({ cls: "working-tabs-children" });
      const isCompletedSection = sentinelId === COMPLETED_PARENT_ID;
      for (const child of children)
        this.renderNode(childWrap, child, 1, isCompletedSection, query);
    }
  }
  // ── Complete / restore ──────────────────────────────────
  /** Marking a tab done closes its live view (it disappears, same as the
   * tab itself closing); unchecking it reopens that view in its group's
   * pane. Checking off the last remaining tab in a group finishes the group
   * too -- no extra confirm dialog, since checking every box one by one is
   * already a deliberate multi-step action. */
  async handleToggleDone(tab) {
    await this.store.toggleDone(tab.id);
    if (tab.done) {
      await this.plugin.leafSync.closeLiveTabOnly(tab);
    } else {
      await this.plugin.leafSync.reopenTab(tab);
    }
    if (!tab.parentId)
      return;
    const group = this.store.find(tab.parentId);
    if (!group || group.type !== "group" || group.parentId === COMPLETED_PARENT_ID)
      return;
    const siblings = this.store.children(group.id);
    if (siblings.length > 0 && siblings.every((s) => s.done)) {
      await this.plugin.leafSync.completeGroup(group.id);
    }
  }
  requestComplete(node) {
    if (!this.store.settings.confirmBeforeComplete) {
      void this.plugin.leafSync.completeGroup(node.id);
      return;
    }
    new ConfirmCompleteModal(this.app, node.title, (dontAskAgain) => {
      if (dontAskAgain)
        void this.store.updateSettings({ confirmBeforeComplete: false });
      void this.plugin.leafSync.completeGroup(node.id);
    }).open();
  }
  /** Deleting a live group/tab record alone doesn't close its actual pane --
   * the leaf stays open, unclaimed, and the very next reconcile pass just
   * spins up a brand-new group for it, making the deleted row "reappear".
   * Detaching the live leaf(s) first, same as Close group/Close tab, avoids
   * that entirely. Sections have no live pane of their own, so this is a
   * no-op for them beyond the plain removal. */
  async deleteNode(node) {
    if (node.type === "tab") {
      await this.plugin.leafSync.closeTab(node);
      return;
    }
    if (node.type === "group")
      await this.plugin.leafSync.closeGroup(node.id);
    await this.store.remove(node.id);
  }
  // ── Keyboard navigation ──────────────────────────────────
  setFocus(id) {
    var _a;
    const prevId = this.focusedId;
    this.focusedId = id;
    if (prevId)
      (_a = this.treeEl.querySelector(`[data-node-id="${prevId}"]`)) == null ? void 0 : _a.removeClass("is-focused");
    const el = this.treeEl.querySelector(`[data-node-id="${id}"]`);
    el == null ? void 0 : el.addClass("is-focused");
    el == null ? void 0 : el.scrollIntoView({ block: "nearest" });
    this.treeEl.focus();
  }
  moveFocus(delta) {
    if (this.visibleOrder.length === 0)
      return;
    const currentIndex = this.focusedId ? this.visibleOrder.indexOf(this.focusedId) : -1;
    const nextIndex = Math.max(0, Math.min(this.visibleOrder.length - 1, currentIndex + delta));
    const nextId = this.visibleOrder[nextIndex];
    if (nextId)
      this.setFocus(nextId);
  }
  handleKeydown(evt) {
    if (!this.focusedId) {
      if (evt.key === "ArrowDown" || evt.key === "ArrowUp") {
        evt.preventDefault();
        this.moveFocus(evt.key === "ArrowDown" ? 1 : -1);
      }
      return;
    }
    const node = this.store.find(this.focusedId);
    if (!node)
      return;
    switch (evt.key) {
      case "ArrowDown":
        evt.preventDefault();
        this.moveFocus(1);
        break;
      case "ArrowUp":
        evt.preventDefault();
        this.moveFocus(-1);
        break;
      case "ArrowRight":
        evt.preventDefault();
        if ((node.type === "group" || node.type === "section") && node.collapsed) {
          void this.store.toggleCollapsed(node.id);
        } else {
          this.moveFocus(1);
        }
        break;
      case "ArrowLeft":
        evt.preventDefault();
        if ((node.type === "group" || node.type === "section") && !node.collapsed) {
          void this.store.toggleCollapsed(node.id);
        } else if (node.parentId && this.store.find(node.parentId)) {
          this.setFocus(node.parentId);
        }
        break;
      case "Enter":
        evt.preventDefault();
        if (node.type === "section")
          void this.store.toggleCollapsed(node.id);
        else if (node.type === "group")
          void this.plugin.leafSync.openGroup(node.id);
        else
          void this.plugin.leafSync.focusTab(node);
        break;
      case "F2": {
        evt.preventDefault();
        const titleEl = this.treeEl.querySelector(`[data-node-id="${node.id}"] .working-tabs-title`);
        if (titleEl)
          this.startRename(titleEl, node);
        break;
      }
      case "Delete":
      case "Backspace":
        evt.preventDefault();
        void this.deleteNode(node);
        break;
    }
  }
  /** Delaying the click action lets a following second click cancel it, so double-clicking the title renames instead of opening/toggling first. */
  wireRowClick(row, action) {
    let pending = null;
    row.addEventListener("click", () => {
      if (pending !== null) {
        window.clearTimeout(pending);
        pending = null;
        return;
      }
      pending = window.setTimeout(() => {
        pending = null;
        action();
      }, 250);
    });
  }
  // ── Inline rename ────────────────────────────────────────
  wireRename(title, node) {
    title.addEventListener("dblclick", (evt) => {
      evt.stopPropagation();
      this.startRename(title, node);
    });
  }
  startRename(title, node) {
    const parent = title.parentElement;
    const input = parent.createEl("input", { cls: "working-tabs-rename-input" });
    input.type = "text";
    input.value = node.title;
    parent.insertBefore(input, title);
    title.remove();
    input.focus();
    input.select();
    const finish = async (commit) => {
      input.removeEventListener("blur", onBlur);
      input.removeEventListener("keydown", onKeydown);
      const value = input.value.trim();
      if (commit && value && value !== node.title) {
        await this.store.rename(node.id, value);
      } else {
        input.replaceWith(title);
      }
    };
    const onBlur = () => void finish(true);
    const onKeydown = (evt) => {
      evt.stopPropagation();
      if (evt.key === "Enter") {
        evt.preventDefault();
        void finish(true);
      } else if (evt.key === "Escape") {
        evt.preventDefault();
        void finish(false);
      }
    };
    input.addEventListener("blur", onBlur);
    input.addEventListener("keydown", onKeydown);
  }
  // ── Create ───────────────────────────────────────────────
  /** No naming modal -- creates instantly with a placeholder title and drops
   * straight into inline rename, since typing a name up front is more
   * friction than the action deserves. Rename (or add a description) later
   * from the row itself if the default doesn't stick. */
  async createSection() {
    const section = await this.store.addSection(this.store.nextDefaultTitle("section"));
    const titleEl = this.treeEl.querySelector(`[data-node-id="${section.id}"] .working-tabs-title`);
    if (titleEl)
      this.startRename(titleEl, section);
  }
  // ── Context menus ────────────────────────────────────────
  showSectionMenu(node, evt) {
    const menu = new import_obsidian4.Menu();
    menu.addItem(
      (item) => item.setTitle("Rename").setIcon("pencil").onClick(() => {
        const titleEl = this.treeEl.querySelector(`[data-node-id="${node.id}"] .working-tabs-title`);
        if (titleEl)
          this.startRename(titleEl, node);
      })
    );
    menu.addItem(
      (item) => item.setTitle("Edit description").setIcon("align-left").onClick(() => {
        var _a;
        new GroupDescriptionModal(
          this.app,
          "Section description",
          "What this section is for\u2026",
          (_a = node.description) != null ? _a : "",
          (description) => {
            void this.store.setDescription(node.id, description || void 0);
          }
        ).open();
      })
    );
    menu.addSeparator();
    menu.addItem(
      (item) => item.setTitle("Delete section").setIcon("trash").onClick(() => {
        if (this.store.children(node.id).length > 0) {
          new import_obsidian4.Notice("Move or complete this section's groups first.");
          return;
        }
        void this.store.remove(node.id);
      })
    );
    menu.showAtMouseEvent(evt);
  }
  showGroupMenu(node, evt, isCompleted) {
    const menu = new import_obsidian4.Menu();
    if (!isCompleted) {
      menu.addItem(
        (item) => item.setTitle("New tab").setIcon("plus").onClick(() => void this.plugin.leafSync.addBlankTab(node.id))
      );
      if (this.plugin.leafSync.isLive(node.id)) {
        menu.addItem(
          (item) => item.setTitle("Close group").setIcon("x").onClick(() => void this.plugin.leafSync.closeGroup(node.id))
        );
      }
    }
    menu.addSeparator();
    menu.addItem(
      (item) => item.setTitle("Rename").setIcon("pencil").onClick(() => {
        const titleEl = this.treeEl.querySelector(`[data-node-id="${node.id}"] .working-tabs-title`);
        if (titleEl)
          this.startRename(titleEl, node);
      })
    );
    menu.addItem(
      (item) => item.setTitle("Edit description").setIcon("align-left").onClick(() => {
        var _a;
        new GroupDescriptionModal(
          this.app,
          "Group description",
          "What this group is for\u2026",
          (_a = node.description) != null ? _a : "",
          (description) => {
            void this.store.setDescription(node.id, description || void 0);
          }
        ).open();
      })
    );
    menu.addSeparator();
    menu.addItem(
      (item) => item.setTitle("Delete permanently").setIcon("trash").onClick(() => void this.deleteNode(node))
    );
    menu.showAtMouseEvent(evt);
  }
  showTabMenu(node, evt) {
    const menu = new import_obsidian4.Menu();
    menu.addItem(
      (item) => item.setTitle(node.done ? "Mark not done" : "Mark done").setIcon("check").onClick(() => void this.store.toggleDone(node.id))
    );
    menu.addSeparator();
    for (const group of this.store.items.filter((n) => n.type === "group" && n.id !== node.parentId)) {
      menu.addItem(
        (item) => item.setTitle(`Move to: ${group.title}`).setIcon("folder").onClick(() => {
          void this.store.moveInto(node.id, group.id, this.store.children(group.id).length);
        })
      );
    }
    menu.addSeparator();
    menu.addItem(
      (item) => item.setTitle("Close tab").setIcon("x").onClick(() => void this.plugin.leafSync.closeTab(node))
    );
    menu.showAtMouseEvent(evt);
  }
  // ── Drag and drop ────────────────────────────────────────
  /** What kind of node is allowed to end up parented at `parentId` (a real group/section id, a sentinel, or null for root). */
  canDropAt(dragged, parentId) {
    if (parentId === null)
      return dragged.type === "group" || dragged.type === "section";
    if (parentId === COMPLETED_PARENT_ID)
      return dragged.type === "group";
    const parent = this.store.find(parentId);
    if ((parent == null ? void 0 : parent.type) === "section")
      return dragged.type === "group";
    if ((parent == null ? void 0 : parent.type) === "group")
      return dragged.type === "tab";
    return false;
  }
  wireDrag(row, node) {
    row.addEventListener("dragstart", (evt) => {
      var _a;
      this.draggedId = node.id;
      row.addClass("working-tabs-dragging");
      (_a = evt.dataTransfer) == null ? void 0 : _a.setData("text/plain", node.id);
      evt.dataTransfer.effectAllowed = "move";
    });
    row.addEventListener("dragend", () => {
      row.removeClass("working-tabs-dragging");
      this.clearDropMarker();
      this.draggedId = null;
    });
    row.addEventListener("dragover", (evt) => {
      if (!this.draggedId || this.draggedId === node.id)
        return;
      const dragged = this.store.find(this.draggedId);
      if (!dragged)
        return;
      const position = this.computeDropPosition(row, node, dragged, evt);
      if (!position)
        return;
      evt.preventDefault();
      this.markDropTarget(row, position);
    });
    row.addEventListener("dragleave", () => this.clearDropMarker());
    row.addEventListener("drop", (evt) => {
      if (!this.draggedId || this.draggedId === node.id)
        return;
      const dragged = this.store.find(this.draggedId);
      if (!dragged)
        return;
      const position = this.computeDropPosition(row, node, dragged, evt);
      if (!position)
        return;
      evt.preventDefault();
      void this.handleDrop(dragged, node, position);
      this.clearDropMarker();
    });
  }
  /** Returns null when this drop wouldn't be valid, so callers can skip preventDefault/marking entirely. */
  computeDropPosition(row, target, dragged, evt) {
    const rect = row.getBoundingClientRect();
    const fraction = (evt.clientY - rect.top) / rect.height;
    const canNestInto = (target.type === "group" || target.type === "section") && this.canDropAt(dragged, target.id);
    if (canNestInto && fraction > 0.25 && fraction < 0.75)
      return "into";
    if (!this.canDropAt(dragged, target.parentId))
      return canNestInto ? "into" : null;
    return fraction < 0.5 ? "before" : "after";
  }
  markDropTarget(row, position) {
    if (this.dropMarkedEl && this.dropMarkedEl !== row)
      this.clearDropMarker();
    row.removeClass("working-tabs-drop-before", "working-tabs-drop-after", "working-tabs-drop-into");
    row.addClass(`working-tabs-drop-${position}`);
    this.dropMarkedEl = row;
  }
  clearDropMarker() {
    var _a;
    (_a = this.dropMarkedEl) == null ? void 0 : _a.removeClass("working-tabs-drop-before", "working-tabs-drop-after", "working-tabs-drop-into");
    this.dropMarkedEl = null;
  }
  async handleDrop(dragged, target, position) {
    if (position === "into") {
      const index2 = this.store.children(target.id).filter((n) => n.id !== dragged.id).length;
      await this.store.moveInto(dragged.id, target.id, index2);
      await this.afterTabMove(dragged);
      return;
    }
    const siblings = this.store.children(target.parentId).filter((n) => n.id !== dragged.id);
    let index = siblings.findIndex((n) => n.id === target.id);
    if (index === -1)
      index = siblings.length;
    if (position === "after")
      index += 1;
    await this.store.moveInto(dragged.id, target.parentId, index);
    await this.afterTabMove(dragged);
  }
  /** A drag that reorders or reparents a tab should be reflected in the
   * actual Obsidian tab strip too, not just the sidebar. */
  async afterTabMove(node) {
    if (node.type === "tab")
      await this.plugin.leafSync.relocateLiveLeaf(node);
  }
  registerRootDropZone(treeEl) {
    treeEl.addEventListener("dragover", (evt) => {
      if (evt.target !== treeEl || !this.draggedId)
        return;
      const dragged = this.store.find(this.draggedId);
      if (dragged && this.canDropAt(dragged, null))
        evt.preventDefault();
    });
    treeEl.addEventListener("drop", (evt) => {
      if (evt.target !== treeEl || !this.draggedId)
        return;
      const dragged = this.store.find(this.draggedId);
      if (!dragged || !this.canDropAt(dragged, null))
        return;
      evt.preventDefault();
      const index = this.store.children(null).filter((n) => n.id !== this.draggedId).length;
      void this.store.moveInto(this.draggedId, null, index);
    });
  }
  /** Lets any group row (dormant or already live) be dragged out of the
   * sidebar and dropped directly onto a pane in the main workspace -- drop
   * near an edge to split that exact pane in that direction, or in the
   * middle to merge in as new tabs there. For an already-live group this
   * doubles as "move this pane elsewhere" (see openGroupAtDropTarget).
   * Registered on the document body via event
   * delegation so it covers every current and future pane without having
   * to hook each one's DOM as it opens/splits/closes; the `.mod-root`
   * scope in the selector below excludes the sidebar docks, same reasoning
   * reconcile already uses to skip them. Uses registerDomEvent (not a raw
   * addEventListener) since body outlives the view and needs cleanup on close. */
  registerWorkspaceDropZones() {
    const rootEl = document.body;
    const paneSelector = ".mod-root .workspace-tabs";
    const resolveZone = (paneEl, evt) => {
      const rect = paneEl.getBoundingClientRect();
      const x = (evt.clientX - rect.left) / rect.width;
      const y = (evt.clientY - rect.top) / rect.height;
      const edge = 0.25;
      if (y < edge)
        return "top";
      if (y > 1 - edge)
        return "bottom";
      if (x < edge)
        return "left";
      if (x > 1 - edge)
        return "right";
      return "center";
    };
    const clearPaneMarker = () => {
      var _a;
      (_a = this.paneDropMarkedEl) == null ? void 0 : _a.removeClass(...PANE_DROP_CLASSES);
      this.paneDropMarkedEl = null;
    };
    const draggedGroup = () => {
      if (!this.draggedId)
        return void 0;
      const dragged = this.store.find(this.draggedId);
      return (dragged == null ? void 0 : dragged.type) === "group" ? dragged : void 0;
    };
    this.registerDomEvent(rootEl, "dragover", (evt) => {
      if (!draggedGroup())
        return;
      const paneEl = evt.target.closest(paneSelector);
      if (!paneEl) {
        clearPaneMarker();
        return;
      }
      evt.preventDefault();
      const zone = resolveZone(paneEl, evt);
      if (this.paneDropMarkedEl && this.paneDropMarkedEl !== paneEl)
        clearPaneMarker();
      paneEl.removeClass(...PANE_DROP_CLASSES);
      paneEl.addClass(`working-tabs-pane-drop-${zone}`);
      this.paneDropMarkedEl = paneEl;
    });
    this.registerDomEvent(rootEl, "dragleave", (evt) => {
      if (this.paneDropMarkedEl && !this.paneDropMarkedEl.contains(evt.relatedTarget))
        clearPaneMarker();
    });
    this.registerDomEvent(rootEl, "drop", (evt) => {
      const dragged = draggedGroup();
      const paneEl = evt.target.closest(paneSelector);
      clearPaneMarker();
      if (!dragged || !paneEl)
        return;
      evt.preventDefault();
      const targetLeaf = this.findLeafForPaneEl(paneEl);
      if (targetLeaf)
        void this.plugin.leafSync.openGroupAtDropTarget(dragged.id, targetLeaf, resolveZone(paneEl, evt));
    });
  }
  findLeafForPaneEl(paneEl) {
    let found;
    this.app.workspace.iterateAllLeaves((l) => {
      if (!found && l.view.containerEl.closest(".mod-root .workspace-tabs") === paneEl)
        found = l;
    });
    return found;
  }
  registerSentinelDropZone(headerEl, sentinelId) {
    headerEl.addEventListener("dragover", (evt) => {
      if (!this.draggedId)
        return;
      const dragged = this.store.find(this.draggedId);
      if (dragged && this.canDropAt(dragged, sentinelId))
        evt.preventDefault();
    });
    headerEl.addEventListener("drop", (evt) => {
      if (!this.draggedId)
        return;
      const dragged = this.store.find(this.draggedId);
      if (!dragged || !this.canDropAt(dragged, sentinelId))
        return;
      evt.preventDefault();
      if (sentinelId === COMPLETED_PARENT_ID && dragged.type === "group") {
        this.requestComplete(dragged);
        return;
      }
      void this.store.moveInto(this.draggedId, sentinelId, this.store.children(sentinelId).length);
    });
  }
};

// src/settings.ts
var import_obsidian5 = require("obsidian");
var TITLE_OVERFLOW_OPTIONS = {
  truncate: "Truncate with ellipsis",
  wrap: "Wrap to multiple lines"
};
var TabSpacesSettingTab = class extends import_obsidian5.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  /** Declarative settings (1.13.0+): gets these into Obsidian's settings search. */
  getSettingDefinitions() {
    return [
      {
        name: "Confirm before completing a group",
        desc: "Ask before marking a group done and moving it to completed. Turn off once you're comfortable -- completed groups can still be restored.",
        control: { type: "toggle", key: "confirmBeforeComplete" }
      },
      {
        name: "Long titles",
        desc: "How to handle tab and group titles (and their descriptions) too long to fit on one line.",
        control: {
          type: "dropdown",
          key: "titleOverflow",
          options: TITLE_OVERFLOW_OPTIONS
        }
      },
      {
        name: "Hide tab bar",
        desc: `Hide Obsidian's native tab-header row across every pane, for a cleaner view. Since that row is also where the native "+" button lives, use each group's "new tab" menu item to open a blank tab instead.`,
        control: { type: "toggle", key: "hideTabHeaders" }
      }
    ];
  }
  getControlValue(key) {
    return this.plugin.store.settings[key];
  }
  async setControlValue(key, value) {
    await this.plugin.store.updateSettings({ [key]: value });
  }
  /** Fallback for Obsidian versions older than 1.13.0. Not called at all once getSettingDefinitions() above is available. */
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian5.Setting(containerEl).setName("Confirm before completing a group").setDesc(
      "Ask before marking a group done and moving it to completed. Turn off once you're comfortable -- completed groups can still be restored."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.store.settings.confirmBeforeComplete).onChange(async (value) => {
        await this.plugin.store.updateSettings({ confirmBeforeComplete: value });
      })
    );
    new import_obsidian5.Setting(containerEl).setName("Long titles").setDesc("How to handle tab and group titles (and their descriptions) too long to fit on one line.").addDropdown((dropdown) => {
      for (const [key, label] of Object.entries(TITLE_OVERFLOW_OPTIONS))
        dropdown.addOption(key, label);
      dropdown.setValue(this.plugin.store.settings.titleOverflow).onChange(async (value) => {
        await this.plugin.store.updateSettings({ titleOverflow: value });
      });
    });
    new import_obsidian5.Setting(containerEl).setName("Hide tab bar").setDesc(
      `Hide Obsidian's native tab-header row across every pane, for a cleaner view. Since that row is also where the native "+" button lives, use each group's "new tab" menu item to open a blank tab instead.`
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.store.settings.hideTabHeaders).onChange(async (value) => {
        await this.plugin.store.updateSettings({ hideTabHeaders: value });
      })
    );
  }
};

// src/main.ts
var TabSpacesPlugin = class extends import_obsidian6.Plugin {
  async onload() {
    this.store = new TabSpacesStore(this);
    await this.store.load();
    this.leafSync = new LeafSync(this, this.store);
    this.leafSync.start();
    this.applyHideTabHeaders();
    this.register(this.store.onChange(() => this.applyHideTabHeaders()));
    this.registerView(VIEW_TYPE_WORKING_TABS, (leaf) => new TabSpacesView(leaf, this));
    this.addRibbonIcon("layout-panel-left", "Open working tabs", () => void this.activateView());
    this.addCommand({
      id: "open-sidebar",
      name: "Open sidebar",
      callback: () => void this.activateView()
    });
    this.addCommand({
      id: "toggle-hide-tab-bar",
      name: "Toggle hide tab bar",
      callback: () => void this.store.updateSettings({ hideTabHeaders: !this.store.settings.hideTabHeaders })
    });
    this.addSettingTab(new TabSpacesSettingTab(this.app, this));
  }
  /** Global appearance preference, not tied to any one pane -- toggled on a
   * body class since Obsidian's tab-header row isn't reachable per-pane
   * without hooking every pane's DOM as it opens/splits/closes. */
  applyHideTabHeaders() {
    document.body.toggleClass("working-tabs-hide-tab-headers", this.store.settings.hideTabHeaders);
  }
  /** Called exactly once, the first time a user turns this plugin on. */
  onUserEnable() {
    void this.activateView();
  }
  async activateView() {
    var _a;
    const { workspace } = this.app;
    let leaf = (_a = workspace.getLeavesOfType(VIEW_TYPE_WORKING_TABS)[0]) != null ? _a : null;
    if (!leaf) {
      leaf = workspace.getLeftLeaf(false);
      await (leaf == null ? void 0 : leaf.setViewState({ type: VIEW_TYPE_WORKING_TABS, active: true }));
    }
    if (leaf)
      await workspace.revealLeaf(leaf);
  }
  onunload() {
    document.body.removeClass("working-tabs-hide-tab-headers");
  }
};
